#ifdef ENABLE_MQTT

#define MQTT_CARD_ID_TOPIC MQTT_START_TOPIC "CARD/UID/"
#define MQTT_CARD_LOGIN_RESULT MQTT_START_TOPIC "CARD/LOGIN/"
#define MQTT_CARD_BLOCK0_TOPIC MQTT_START_TOPIC "CARD/BLOCK/0"
#define MQTT_CARD_BLOCK1_TOPIC MQTT_START_TOPIC "CARD/BLOCK/1"
#define MQTT_CARD_BLOCK2_TOPIC MQTT_START_TOPIC "CARD/BLOCK/2"
#define MQTT_CARD_READED_TIME MQTT_START_TOPIC  "CARD/UPTIME_REF"

#define MQTT_INPUT_STATUS MQTT_START_TOPIC "INPUT/1/ST"
#define MQTT_TAMPER_STATUS MQTT_START_TOPIC "INPUT/TAMPER/ST"


#define MQTT_OUTPUT_RELE_TRIGGER MQTT_START_TOPIC "OUTPUT/RELE/1/TRG" 
#define MQTT_OUTPUT_RELE_STATUS MQTT_START_TOPIC "OUTPUT/RELE/1/ST"

#define MQTT_OUTPUT_LED1_STATUS MQTT_START_TOPIC "OUTPUT/LED/1/ST"
//#define MQTT_OUTPUT_LED1_TRG MQTT_START_TOPIC "OUTPUT/LED/1/TRG" 

#define MQTT_OUTPUT_LED2_STATUS MQTT_START_TOPIC "OUTPUT/LED/2/ST"
//#define MQTT_OUTPUT_LED2_TRG MQTT_START_TOPIC "OUTPUT/LED/2/TRG"

#define MQTT_SYS_INFORMATION_TIME MQTT_START_TOPIC "SYS/INFO/UPTIME"
#define MQTT_SYS_INFORMATION_FWVERS MQTT_START_TOPIC "SYS/INFO/VERS_FW"
//#define MQTT_SYS_INFORMATION_DISABELNFC MQTT_START_TOPIC "SYS/RULE/NFC"  



#include <PubSubClient.h>

PubSubClient mqtt(mqttClient);

enum st_mqtt {
  MQTT_STARTUP,
  MQTT_CONNECT,  //Si collega con il server MQTT
  MQTT_DISCONNECT,
  MQTT_SUBSCRIBE,  //Sub scribe all topic
  MQTT_PUBLISH_ONESHOT,

  MQTT_CHECK_CONNECTION  //Controlla che la connessione al server mqtt sia ancora in corso
};
uint8_t st_mqtt_index = MQTT_STARTUP;
void MQTT_loop();

void mqtt_send_badge(NFC_CARD *card);
void mqtt_output_status(OUTPUT_INFO my_output[3]);
void mqtt_input_status(INPUT_INFO my_input[2]);

void mqtt_callback(char* topic, byte* payload, unsigned int length);

#endif